name: Scheduled Selenium Tests

on:
  schedule:
    - cron: "30 22 * * 5"  # Every Friday at 10:30 PM UTC
  workflow_dispatch:        # allows manual trigger

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Selenium test
        run: python tests/test_google.py
